[package]
name = "testserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcp_diff = { path = "../../tcp_diffuser", version = "0.1.0" }
